apiVersion: v1
kind: Service
metadata:
  name: bookstore-backend-svc
spec:
  selector:
    app: bookstore-backend
  ports:
  - port: {{ .Values.backend.port }}
    targetPort: {{ .Values.backend.port }}
