apiVersion: v1
kind: Service
metadata:
  name: bookstore-frontend-svc
spec:
  type: ClusterIP
  selector:
    app: bookstore-frontend
  ports:
  - port: {{ .Values.frontend.port }}
    targetPort: {{ .Values.frontend.port }}
