apiVersion: v1
kind: Service
metadata:
  name: bookstore-postgres
spec:
  selector:
    app: bookstore-postgres
  ports:
  - port: {{ .Values.postgres.port }}
    targetPort: {{ .Values.postgres.port }}
