apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookstore-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bookstore-frontend
  template:
    metadata:
      labels:
        app: bookstore-frontend
    spec:
      nodeSelector:
        role: bookstore
      containers:
      - name: frontend
        image: amanbhatnagar/angular-demo:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: bookstore-frontend-lb
spec:
  type: LoadBalancer
  selector:
    app: bookstore-frontend
  ports:
  - port: 80
    targetPort: 80
