apiVersion: v1
kind: Pod
metadata:
  name: bookstore-postgres
  labels:
    app: bookstore-postgres
spec:
  nodeSelector:
    role: bookstore
  containers:
  - name: postgres
    image: postgres:15
    env:
    - name: POSTGRES_USER
      value: "bookstore"
    - name: POSTGRES_PASSWORD
      value: "bookstore"
    - name: POSTGRES_DB
      value: "bookstore"
    ports:
    - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: bookstore-postgres
spec:
  selector:
    app: bookstore-postgres
  ports:
  - port: 5432
    targetPort: 5432
