apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: bookstore
  namespace: monitoring
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: bookstore-backend
  endpoints:
  - port: http
    interval: 15s

